spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yw_book?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 12345!